#!/bin/bash
python3 -m venv env && source env/bin/activate && \
    pip3 install cython numpy jupyter ipython flask scipy pandas requests flask $TF_BINARY_URL keras gym && \
deactivate
echo "👌  done"
